language: python

python:
  - "3.5"

services:
  - docker
  - docker-compose

jobs:
  include:
    - stage: test
      script: 
        - echo "No tests yet"
    - stage: build base
      script:
        - docker build -t test .
        - docker run -it -e username=$MON_USERNAME test
